name: Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: push
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          ARGS: "${{ vars.DEPLOY_RSYNC_ARGS }}"
          SOURCE: ${{ vars.DEPLOY_LOCAL_SOURCE }}
          REMOTE_HOST: ${{ secrets.DEPLOY_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_REMOTE_USER }}
          TARGET: ${{ secrets.DEPLOY_REMOTE_TARGET }}
          EXCLUDE: "${{ vars.DEPLOY_RSYNC_EXCLUDE }}"
          SCRIPT_AFTER: |
            ls -lahR ${{ secrets.DEPLOY_REMOTE_TARGET }}
            echo $RSYNC_STDOUT
